# Generated by Django 2.2 on 2020-07-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_by',
            field=models.IntegerField(default=None),
        ),
    ]
