# Generated by Django 2.2 on 2020-07-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200721_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='address',
            name='last_updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='landline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='landline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='landline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
