# Generated by Django 2.2 on 2020-07-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200722_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
