# Generated by Django 2.2 on 2020-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200809_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoketake',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
