# Generated by Django 2.2 on 2020-07-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10000)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField()),
                ('created_by', models.IntegerField(default=None)),
                ('updated_by', models.IntegerField(default=None)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10000)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField()),
                ('created_by', models.IntegerField(default=None)),
                ('updated_by', models.IntegerField(default=None)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField()),
                ('created_by', models.IntegerField(default=None)),
                ('updated_by', models.IntegerField(default=None)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SalesOrder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField()),
                ('created_by', models.IntegerField(default=None)),
                ('updated_by', models.IntegerField(default=None)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PurchaseOder')),
            ],
        ),
    ]
