# Generated by Django 2.2 on 2020-07-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200721_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseoder',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='purchasetransaction',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='salestransaction',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='purchaseoder',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='purchasetransaction',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='purchaseoder',
            name='last_updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='last_updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='last_updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='last_updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseoder',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
