# Generated by Django 2.2 on 2020-07-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200722_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salestransaction',
            old_name='purchase_order',
            new_name='sales_order',
        ),
    ]
