# Generated by Django 2.2 on 2020-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200809_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
