# Generated by Django 2.2 on 2020-08-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200810_1215'),
        ('orders', '0011_auto_20200810_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseoder',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
