# Generated by Django 2.2 on 2020-08-10 12:30

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200810_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoder',
            name='total_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EGP', max_digits=14, null=True),
        ),
    ]
